[project]
name = "charlotte"
version = "1.1.0"
description = "A cutscene encoder tool for a certain popular anime game."
authors = [{ name = "lunarmint", email = "me@chocomint.dev" }]
requires-python = ">=3.14"
readme = "README.md"
maintainers = [{ name = "Mint" }]
dependencies = [
    "numpy>=2.5.3",
    "orjson>=3.12.0",
    "pycryptodome>=3.23.0",
    "typer>=0.27.2",
    "urllib3>=2.8.0",
    "vapoursynth>=80",
    "vapoursynth-akarin>=1.5.0",
    "vapoursynth-bestsource>=22.0",
    "vapoursynth-deblock>=9.0",
    "vapoursynth-edgemasks>=4.0",
    "vapoursynth-resize2>=0.5.1",
    "vapoursynth-vszip>=22.1.0",
    "vapoursynth-zsmooth>=0.20.0",
    "vs-placebo>=2.0.4",
    "vsjetpack>=2.2.4",
]

[dependency-groups]
dev = [
    "deptry>=0.25.1",
    "pytest>=9.1.1",
    "ruff>=0.15.22",
    "vsview>=0.11.0",
]
build = [
    "pyinstaller>=6.22.3",
]

[[tool.uv.index]]
name = "vs-wheels"
url = "https://jaded-encoding-thaumaturgy.github.io/vs-wheels/simple"

[tool.uv]
package = false
default-groups = [
    "dev",
    "build",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.deptry]
known_first_party = ["preview"]
per_rule_ignores = { DEP003 = ["rich"], DEP004 = ["vsview"] }

[tool.ruff]
line-length = 100
src = [".", "tests"]

[tool.ruff.lint]
select = [
    "ASYNC", # flake8-async
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "DTZ", # flake8-datetimez (enforce timezone-aware datetimes)
    "E", # pycodestyle rules
    "F", # pyflakes rules
    "I", # isort rules
    "PERF", # (perflint) prevent performance anti-patterns
    "PLE", # pylint errors
    "PLW", # pylint rules
    "PIE", # flake8-pie (misc. lints for cleaner code)
    "RUF", # ruff-specific rules (catch common mistakes)
    "N", # pep8-naming
    "Q", # flake8-quotes
    "RSE", # flake8-raise (simplify raise statements)
    "RET", # flake8-return (simplify return statements)
    "SIM", # flake8-simplify (suggest simpler code)
    "TCH", # flake8-type-checking
    "TID", # flake8-tidy-imports
    "T20", # (disallow print statements) keep debugging statements out of the codebase
    "W", # pycodestyle warnings
    "UP", # (pyupgrade) auto-upgrade syntax to newer versions of Python
]

extend-safe-fixes = [
    "TCH", # move import from and to TYPE_CHECKING blocks
]

[tool.ruff.lint.isort]
lines-between-types = 1
lines-after-imports = 2

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.ruff.lint.pydocstyle]
convention = "google"
